### ISSUE TITLE
auto_conv script refers to non-existing file

### ISSUE THREAD

**Issue by eiennohito** [ku-nlp/KyotoCorpus#8]
https://github.com/ku-nlp/KyotoCorpus/blob/78513bdd5bc25dc58ede7c7f12bb1bdddd0c5edb/auto_conv#L82

cf https://github.com/ku-nlp/jumanpp-jumandic/issues/4

**Comment by eiennohito** [comment]
@nobu-g please check

**Comment by eiennohito** [comment]
Probably it should be `$BASE_DIR/id/full/all.id`

**Comment by nobu-g** [comment]
I fixed the issue. Please check.
https://github.com/ku-nlp/KyotoCorpus/commit/e3d3b28c379f6e8b47c60831c0c5317d65871e1d
